from enum import StrEnum


class ApiErrorCode(StrEnum):
    CANCELLATION_PENDING = "CANCELLATION_PENDING"
    EVENT_HISTORY_EXPIRED = "EVENT_HISTORY_EXPIRED"
    EXTERNAL_MODIFICATION_CONFLICT = "EXTERNAL_MODIFICATION_CONFLICT"
    INCOMPLETE_ANALYSIS = "INCOMPLETE_ANALYSIS"
    INPUT_SECURITY_REJECTION = "INPUT_SECURITY_REJECTION"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    INVALID_ENTITY_ID = "INVALID_ENTITY_ID"
    INVALID_REQUEST = "INVALID_REQUEST"
    MAPPING_MERGE_CONFLICT = "MAPPING_MERGE_CONFLICT"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    NOT_FOUND = "NOT_FOUND"
    OPERATION_NOT_IMPLEMENTED = "OPERATION_NOT_IMPLEMENTED"
    PROJECT_BUSY = "PROJECT_BUSY"
    PROJECT_LOAD_FAILED = "PROJECT_LOAD_FAILED"
    PROJECT_NOT_READY = "PROJECT_NOT_READY"
    RESOURCE_LIMIT = "RESOURCE_LIMIT"
    SERVICE_SHUTTING_DOWN = "SERVICE_SHUTTING_DOWN"
    STALE_REVISION = "STALE_REVISION"
    UNSUPPORTED_CAPABILITY = "UNSUPPORTED_CAPABILITY"

    def __str__(self) -> str:
        return str(self.value)
